config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),

    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from .views import contact_page, contact_form_save

app_name = 'contacts'

urlpatterns = [
    path('', contact_page, name='contact_page'),
    path('form_save/', contact_form_save, name='contact_form_save')
]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

contacts/models.py
from django.db import models
from persons.models import PersonAbstract


# Create your models here.

class ContactPage(models.Model):
    description = models.CharField(verbose_name='Описание', max_length=250, blank=True)
    office = models.CharField(verbose_name='Офис', max_length=150, blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=50, blank=True)
    email = models.EmailField(verbose_name='Email')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self) -> str:
        return f'{self.description}'


class ContactPageForm(PersonAbstract):
    subject = models.CharField(verbose_name='Тема', max_length=100)
    message = models.TextField(verbose_name='Текст сообщения')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self) -> str:
        return f'{self.subject}'

contacts/forms.py
from django import forms
from .models import ContactPageForm


# class ContactForm(forms.Form):
#     first_name = forms.CharField(label='Имя', help_text='Имя', max_length=150, required=True)
#     last_name = forms.CharField(label='Фамилия', help_text='Фамилия', max_length=150,
#                                 required=True)
#     email = forms.EmailField(label='e-mail', help_text='e-mail', required=True)
#     phone = forms.CharField(label='Телефон', help_text='Телефон', max_length=14, required=True)
#     subject = forms.CharField(label='Тема', help_text='Тема', max_length=100, required=True)
#     message = forms.CharField(label='Текст сообщения', help_text='Текст сообщения', widget=forms.Textarea)
#

class ContactFormDB(forms.ModelForm):
    class Meta:
        model = ContactPageForm
        fields = ('subject', 'first_name', 'last_name', 'phone', 'email', 'message')

        widgets = {
            'subject': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Предмет сообщения'
            }),
            'first_name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Имя'
            }),
            'last_name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Фамилия'
            }),
            'phone': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Телефон'
            }),
            'email': forms.EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
            }),
            'message': forms.Textarea(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Сообщение'
            }),
        }

contacts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.decorators.http import require_http_methods
from django.urls import reverse

from .forms import ContactFormDB
from .models import ContactPage, ContactPageForm

from icecream import ic

# Create your views here.

def contact_page(request):
    template_ = 'contact_page.html'
    contact_page = get_object_or_404(ContactPage, pk=1)
    # contact_form = ContactForm();
    contact_form_db = ContactFormDB()

    context = {
        'contact_page': contact_page,
        # 'contact_form': contact_form,
        'contact_form_db': contact_form_db,
    }

    return render(request=request, template_name=template_, context=context)


@require_http_methods(["GET", "POST"])
def contact_form_save(request):

    if request.method in 'POST':
        form = ContactFormDB(request.POST)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse('contacts:contact_page'))

contacts/templates/contact_page.html
{% extends 'layout/base.html' %}

{% block title %}
    Контактная информация
{% endblock title %}

{% block content %}
    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Контакты</h6>
                <h1 class="mb-5">Контактная информация</h1>
            </div>
            <div class="row g-4">
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <h5>Контакты</h5>
                    <h4 class="mb-4">{{ contact_page.description }}</h4>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary"
                             style="width: 50px; height: 50px;">
                            <i class="fa fa-map-marker-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Офис</h5>
                            <p class="mb-0">{{ contact_page.office }}</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center mb-3">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary"
                             style="width: 50px; height: 50px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Mobile</h5>
                            <p class="mb-0">{{ contact_page.phone }}</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary"
                             style="width: 50px; height: 50px;">
                            <i class="fa fa-envelope-open text-white"></i>
                        </div>
                        <div class="ms-3">
                            <h5 class="text-primary">Email</h5>
                            <p class="mb-0">{{ contact_page.email }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                    <iframe class="position-relative rounded w-100 h-100"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                            frameborder="0" style="min-height: 300px; border:0;" allowfullscreen="" aria-hidden="false"
                            tabindex="0"></iframe>
                </div>
                <div class="col-lg-4 col-md-12 wow fadeInUp" data-wow-delay="0.5s">
                    <form action="{% url 'contacts:contact_form_save' %}" method="post">{% csrf_token %}
                        {#                        {{ contact_form.as_p }}#}
                        <div class="row g-3">
                            {{ contact_form_db.as_table }}
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Отправить сообщение</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}