config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),

    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subjects/urls.py
from django.urls import path

from teachers.urls import app_name

from .views import SubjectListView, SubjectTemplateView, SubjectAddView,\
        SubjectUptadeView, SubjectDeleteView
# from classboard.views import filter_students_group

app_name = 'subjects'

urlpatterns = [
    path('',SubjectListView.as_view() , name='subjects_view'),
    path('<int:pk>/', SubjectTemplateView.as_view(), name='subjects_view'),
    path('add', SubjectAddView.as_view(), name='subject_add'),
    path('<int:pk>/uptade', SubjectUptadeView.as_view(), name='subject_uptade' ),
    path('<int:pk>/delete', SubjectDeleteView.as_view(), name='subject_delete'),
    # # path('with_teacher/', show_classes_teacher, name='show_classes_teacher'),
    # # path('with_teacher/<int:pk>', show_classes_teacher, name='show_classes_teacher'),
    # # path('with_teacher', class_view, name='class_view'),
    # path('change_teacher/<int:pk>/<int:tpk>', change_teacher, name='change_teacher'),
    # # path('filter_group/', filter_students_group, name='filter_students_group'),
]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

subjects/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from students.models import Group


class SubjectAbstract(models.Model):
    name = models.CharField(verbose_name='Название предмета', max_length=100)

    class Meta:
        abstract = True

        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'

    def __str__(self) -> str:
        return f'{self.name}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("subjects:subjects_view", kwargs={"pk": self.pk})


class Subject(SubjectAbstract):
    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

    def __str__(self) -> str:
        return f'{self.name}'


class SubjectPairChoices(models.TextChoices):
    PAIR_1 = 1, _('Первая пара')
    PAIR_2 = 2, _('Вторая пара')
    PAIR_3 = 3, _('Третья пара')
    PAIR_4 = 4, _('Четвертая пара')
    PAIR_5 = 5, _('Пятая пара')
    PAIR_6 = 6, _('Шестая пара')
    PAIR_7 = 7, _('Седьмая пара')
    PAIR_8 = 8, _('Восьмая пара')


class SubjectByDayChoices(models.TextChoices):
    MO = 1, _('Понедельник')
    TU = 2, _('Вторник')
    WE = 3, _('Среда')
    TH = 4, _('Четверг')
    FR = 5, _('Пятница')
    SA = 6, _('Суббота')
    SU = 7, _('Воскресенье')

subjects/forms.py
from django import forms
from .models import Subject
class SubjectAddForm(forms.ModelForm):
  

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Subject
        fields = ('name',)

subjects/views.py
from django.shortcuts import render, get_object_or_404

from .models import Subject
from teachers.models import Teacher
from django.views.generic.base import TemplateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from .forms import SubjectAddForm

# Create your views here.

# def subjects_view(request, pk=None) -> render:
#     if pk:
#         template = 'subject_detail.html'
#         subject = get_object_or_404(Subject, pk=pk)
#         context = {
#             'subject': subject,
#             'subject_teachers' : subject.subject_teacher.all()
#         }
#     else:
#         template = 'subjects.html'
#         classes = Subject.objects.all()
#         teachers = Teacher.objects.all()
#         context = {
#             'subjects': classes,
            
#         }
        
#     return render(request=request, template_name=template, context=context)
    
    
# def subjects_delete(request, pk) -> render:
#     template = 'subjects.html'
    
#     class_ = get_object_or_404(Subject, pk=pk)
    
#     class_.delete()
    
#     classes = Subject.objects.all()
        
#     context = {
#         'subjects': classes,
#     }
    
#     return render(request=request, template_name=template, context=context)
    
# def change_teacher(request, pk, tpk) -> render:
#     template = 'subjects.html'

    
#     subject = get_object_or_404(Subject, pk=pk)
#     teacher = get_object_or_404(Teacher, pk=tpk)
    
#     subject.teacher = teacher
#     subject.save()
    
#     # class_ = Class.objects.filter(pk=pk).update(teacher=teacher)
    
#     subjects = Subject.objects.all()
#     teachers = Teacher.objects.all()

#     # teachers = Teacher.objects.filter(Q(pk__lte=3))
    
#     context = {
#         'subjects': subjects,
#         'teachers': teachers,
#     }

#     return render(request=request, template_name=template, context=context)

# # def show_classes_teacher(request, pk=None) -> render:
# #     if pk:
# #         template = 'classes_with_teachers_detail.html'
# #         class_ = get_object_or_404(ClassWithTeacher, pk=pk)
# #
# #         teacher_first_name = []
# #         q_ = Q(teacher__first_name='Кравец') | Q(teacher__first_name='Макаренко')
# #
# #
# #         for teacher_first_name_item in ClassWithTeacher.objects.filter(teacher__first_name='Кравец').prefetch_related().values('teacher__first_name', 'teacher__last_name'):
# #         # for teacher_first_name_item in ClassWithTeacher.objects.filter().prefetch_related().values('teacher__first_name', 'teacher__last_name'):
# #         # for teacher_first_name_item in ClassWithTeacher.objects.filter().prefetch_related().values('teacher__first_name', 'teacher__last_name').distinct():
# #             teacher_first_name.append(teacher_first_name_item)
# #
# #         context = {
# #             'class': class_,
# #             'teacher_first_name': teacher_first_name,
# #         }
# #     else:
# #         template = 'classes_with_teachers.html'
# #
# #
# #         # class_.teacher = teacher
# #         # class_.save()
# #
# #         # class_ = Class.objects.filter(pk=pk).update(teacher=teacher)
# #
# #         subjects = ClassWithTeacher.objects.all()
# #         teachers = Teacher.objects.all()
# #
# #
# #
# #         # teachers = Teacher.objects.filter(Q(pk__lte=3))
# #
# #         context = {
# #             'subjects': subjects,
# #             'teachers': teachers,
# #         }
# #
# #     return render(request=request, template_name=template, context=context)

class SubjectListView(ListView):
    model = Subject
    template_name = 'subjects.html'
    context_object_name = 'subjects'

    def get_queryset(self):
        qs = {
            'subjects' : Subject.objects.all()
        }
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subjects'] = self.get_queryset()['subjects']

        return context
    
class SubjectTemplateView(TemplateView):
    template_name = 'subject_detail.html'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['subject'] = get_object_or_404(Subject, pk = self.kwargs['pk'])

        return context

class SubjectAddView(CreateView):
    model = Subject
    success_url = '/subjects/'
    template_name = 'subject_add.html'
    form_class = SubjectAddForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    def form_invalid(self, form):
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            form.save(commit=True)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class SubjectUptadeView(UpdateView):
    model = Subject
    success_url = '/subjects/'
    template_name = 'subject_add.html'
    form_class = SubjectAddForm

class SubjectDeleteView(DeleteView):
    model = Subject
    success_url = '/subjects/'
    template_name = 'subject_delete.html'

subjects/templates/classes_with_teachers.html
{% extends "layout/base.html" %}

{% block title %}
    Занятия
{% endblock title %}
    
{% block content %}
     {% for class in classes %}
        <h3>{{ class.name }}</h3>
        <h4>Преподаватели: </h4>

        {% for teacher in class.teacher.all %}
        <p>
            {{ teacher.first_name }} {{ teacher.last_name }}
        </p>
        {% endfor %}
        <a class="btn btn-primary" href="{% url 'subjects:show_classes_teacher' class.pk %}"> Перейти </a>
        {% comment %} <a class="btn btn-success" href="{% url 'subjects:class_view' class.pk %}"> Перейти </a>     {% endcomment %}
        <a class="btn btn-danger" href="{% url 'classes:class_delete' class.pk %}"> Удалить </a>    


     {% endfor %}
    
{% endblock content %}

subjects/templates/classes_with_teachers_detail.html
{% extends "layout/base.html" %}

{% block title %}
    Занятие с учителем
{% endblock title %}
    
{% block content %}

        <h3>{{ subject.name }}</h3>
        <h4>Преподаватели: </h4>
        {% for item in teacher_first_name %}

        <p>
            {{ item.teacher__first_name }} {{ item.teacher__last_name }}
        </p>
        {% endfor %}

        <a class="btn btn-primary" href="{% url 'subjects:show_classes_teacher' %}"> Перейти </a>
        {% comment %} <a class="btn btn-success" href="{% url 'subjects:class_view' class.pk %}"> Перейти </a>     {% endcomment %}

    
{% endblock content %}

subjects/templates/subject_add.html
{% extends 'layout/base.html' %} 
{% block title %} Добавить предмет {% endblock title %} 

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Добавить прдемет</h3>
        <div class="row">
          <div class="col-md-12">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %} {{ form.as_p }}
              <button type="submit" class="btn btn-primary">
                Отправить
              </button>
              <a class="btn btn-info" href="{% url 'subjects:subjects_view' %}">Список предметов</a>
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  
{% endblock content %}

subjects/templates/subject_delete.html
{% extends 'layout/base.html' %}
{% block title %}
    Удалить {{ object }}
{% endblock title %}
    

{% block content %}
    <form action="{% url 'subjects:subject_delete' object.pk %}" method="post">
        {% csrf_token %} 
        <h3>Вы уверены, что хотите удалить предмет {{ object }}?</h3>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'subjects:subjects_view' %}" class="btn btn-primary">Отмена</a>
    </form>
{% endblock content %}
    

subjects/templates/subject_detail.html
{% extends "layout/base.html" %}

{% block title %}
    {{ class.name }}
{% endblock title %}
    
{% block content %}
    <h3>{{ subject.name }}</h3>
    
    {% for teacher in  subject.subject_teacher.all %}
        <h6>{{ teacher }}</h6>
    {% endfor %}
    <a class="btn btn-info" href="{% url 'subjects:subject_uptade' subject.pk %}">Изменить</a> 
    <a class="btn btn-danger" href="{% url 'subjects:subject_delete' subject.pk %}">Удалить</a> 
    <a class="btn btn-info" href="{% url 'subjects:subjects_view' %}">Обратно</a>
{% endblock content %}
    

subjects/templates/subjects.html
{% extends "layout/base.html" %}

{% block title %}
    Занятия
{% endblock title %}
    
{% block content %}
<table class="table table-striped container-fluid mt-5">
     {% for subject in subjects %}
        <tr>
            <td>
                <a href="{{ subject.get_absolute_url }}">{{ subject.name }}</a>
            </td>
            
            {% for teacher in subject.subject_teacher.all %}
                <td>
                    {{ teacher }}
                </td>
            {% endfor %}
                
        </tr>
        
        

     {% endfor %}

    </table>
    <a class="btn btn-primary" href="{% url 'subjects:subject_add' %}">Добавить предмет</a>
{% endblock content %}