config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),

    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

wages/models.py
import datetime
from django.db import models

from django.utils.translation import gettext_lazy as _


def year_choices() -> list:
    return [(r, r) for r in range(1984, datetime.date.today().year+1)]

def current_year():
    return datetime.date.today().year

def month_choices() -> list:
    return [(r, r) for r in range(1, 13)]

def current_month():
    return str(datetime.date.today().month)


class Wage(models.Model):
    """Модель таблицы заработной платы учителя
    """
    teacher = models.ForeignKey(verbose_name=_('Преподаватель'),
                                    to='teachers.Teacher',
                                    on_delete=models.CASCADE,
                                    related_name='teachers_wage')
    salary = models.DecimalField(verbose_name=_('Оклад'),
                                    max_digits=10,
                                    decimal_places=2,
                                    blank=True,
                                    null=True)
    tax = models.PositiveSmallIntegerField(verbose_name=_('Налог %'),
                                    blank=True,
                                    null=True,
                                    default=12)
    deductions = models.DecimalField(verbose_name=_('Вычеты'),
                                    max_digits=10,
                                    decimal_places=2,
                                    blank=True,
                                    null=True,
                                    default=0)
    alimony = models.PositiveSmallIntegerField(verbose_name=_('Алименты %'),
                                    blank=True,
                                    null=True)
    net = models.DecimalField(verbose_name=_('На руки'),
                                    max_digits=10,
                                    decimal_places=2,
                                    blank=True)
    year = models.PositiveSmallIntegerField(verbose_name=_('Год'),
                                    choices=year_choices(),
                                    default=current_year())
    month = models.PositiveSmallIntegerField(verbose_name=_('Месяц'),
                                    choices=month_choices(),
                                    default=current_month())

    created_at = models.DateField(verbose_name=_('Дата создания'),
                                    auto_now_add=True)
    updated_at = models.DateField(verbose_name=_('Дата изменения'),
                                    auto_now=True)
    
    class Meta:
        verbose_name = 'Заработная плата'
        verbose_name_plural = 'Заработная плата'
        
        ordering = ['teacher', ]
        
    def __str__(self) -> str:
        return f'{self.teacher}'
    
    def save(self, *args, **kwargs):
        """
        При сохраниении происходит расчёт заработной платы послее отчислений
        и налогов (net)
        """
        if self.salary:
            tax = self.salary / 100 * self.tax if self.tax else 0
            alimony = self.salary / 100 * self.alimony if self.alimony else 0
        
            self.net = self.salary - tax - self.deductions - alimony 
        else:
            self.net = 0

        super(Wage, self).save(*args, **kwargs)

wages/views.py
import datetime
from django.db.models import Count, Sum, Q, F
from django.shortcuts import render, get_object_or_404
from wages.models import Wage

# Create your views here.


def get_grid_title() -> dict:
    header = {
        'teacher_title': Wage._meta.get_field('teacher').verbose_name,
        'salary_title': Wage._meta.get_field('salary').verbose_name,
        'tax_title': Wage._meta.get_field('tax').verbose_name,
        'deductions_title': Wage._meta.get_field('deductions').verbose_name,
        'alimony_title': Wage._meta.get_field('alimony').verbose_name,
        'net_title': Wage._meta.get_field('net').verbose_name,
        'go_to': 'Перейти',
        're_calculate': 'Пересчитать',
    }
    return header

   
def show_teachers_grid(request, pk=None):
    if not pk:
        template_ = 'wages_index.html'
        today_date = Q(year=datetime.date.today().year) | \
                     Q(month=datetime.date.today().month)
        q_records = Q(deductions__gt=0) & Q(pk__gte=2)
        
        teacher = Wage.objects.select_related().filter(today_date).all()
        
        annotates = Wage.objects.select_related().annotate(
                annotate_teacher=(F('teacher__first_name')),
                annotate_pk=Count('pk', filter=q_records),
                annotate_salary=Sum('salary', filter=q_records),
                annotate_deductions=Sum('deductions', filter=q_records),
                annotate_net=Sum('net', filter=q_records),
                annotate_tax_count=F('salary')/100 * F('tax'),
                annotate_alimony_count=F('salary')/100 * F('alimony'),
            ).order_by('-deductions')
        
        totals = Wage.objects.select_related().filter(today_date).\
                order_by('-deductions').\
                aggregate(Count('pk'),
                    Sum('salary'),
                    Sum('deductions'),
                    Sum('net'))

        context = {
            'header': get_grid_title(),
            'teacher': teacher,
            'totals': totals,
            'annotates': annotates
        }
        
    return render(request=request, template_name=template_, context=context)


def wage_recalculate(request, pk=None):

    template_ = 'wages_index.html'
    
    teacher = get_object_or_404(Wage, pk=pk)
    teacher.save()
    
    teacher = Wage.objects.all()
    context = {
        'header': get_grid_title(),
        'teacher': teacher,
    }
        
    return render(request=request, template_name=template_, context=context)
   

wages/templates/wages_index.html
{% extends 'layout/base.html' %}


{% block title %}
    Заработная плата преподавателей
{% endblock title %}
    

{% block content %}
    {% if user.is_authenticated %}
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">{{ header.teacher_title }}</th>
                <th scope="col">{{ header.salary_title }}</th>
                <th scope="col">{{ header.tax_title }}</th>
                <th scope="col">{{ header.deductions_title }}</th>
                <th scope="col">{{ header.alimony_title }}</th>
                <th scope="col">{{ header.net_title }}</th>
                <th scope="col">{{ header.go_to }}</th>
                <th scope="col">{{ header.re_calculate }}</th>
                </tr>
            </thead>
            <tbody>
            {% for teacher_item in teacher %}
                <tr>
                    <td>
                        {{ teacher_item.teacher }}
                    </td>
                    <td>
                        {{ teacher_item.salary }}
                    </td>
                    <td>
                        {{ teacher_item.tax }}
                    </td>
                    <td>
                        {{ teacher_item.deductions }}
                    </td>
                    <td>
                        {{ teacher_item.alimony }}
                    </td>
                    <td>
                        {{ teacher_item.net }}
                    </td>
                    <td>
                        <a class='btn btn-primary' href="{% url 'wages:show_teachers_grid' teacher_item.pk %}"> Перейти </a>
                    </td>
                    <td>
                        <a class='btn btn-success' href="{% url 'wages:wage_recalculate' teacher_item.pk %}"> Пересчитать </a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td>
                    Всего: {{ totals.pk__count}}
                </td>
                <td>
                    {{ totals.salary__sum|floatformat:2 }}
                </td>
                <td>
                </td>
                <td>
                    {{ totals.deductions__sum|floatformat:2 }}
                </td>
                <td>
                </td>
                <td>
                    {{ totals.net__sum|floatformat:2 }}
                </td>
                <td>
                    {% comment %} <a class='btn btn-primary' href="{% url 'wages:show_teachers_grid' teacher_item.pk %}"> Перейти </a> {% endcomment %}
                </td>
                <td>
                    {% comment %} <a class='btn btn-success' href="{% url 'wages:wage_recalculate' teacher_item.pk %}"> Пересчитать </a> {% endcomment %}
                </td>
            </tr>
                {% for annotate in annotates %}
                    {% if annotate.annotate_pk %}
                        <tr>
                            <td>
                                {{ annotate.annotate_teacher}} 
                        </td>
                        <td>
                           
                        </td>
                        <td>
                            {{ annotate.annotate_tax_count|floatformat:2 }}
                        </td>
                        <td>
                            {% comment %} {{ annotate.annotate_deductions|floatformat:2 }} {% endcomment %}
                        </td>
                        <td>
                            {{ annotate.annotate_alimony_count|floatformat:2 }}

                        </td>
                        <td>
                            {{ annotate.annotate_net|floatformat:2 }}
                        </td>
                        <td>
                            {% comment %} <a class='btn btn-primary' href="{% url 'wages:show_teachers_grid' teacher_item.pk %}"> Перейти </a> {% endcomment %}
                        </td>
                        <td>
                            {% comment %} <a class='btn btn-success' href="{% url 'wages:wage_recalculate' teacher_item.pk %}"> Пересчитать </a> {% endcomment %}
                        </td>
                    {% endif %}
            </tr>
            {% endfor %}
        
            </tbody>
        </table>
    {% else %}
        <h2>Вам запрещено просматривать данную страницу</h2>
    {% endif %}
{% endblock content %}
    