config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teachers/', include('teachers.urls', namespace='teachers.teachers')),
    path('subjects/', include('subjects.urls', namespace='subjects.subjects')),
    path('classboard/', include('classboard.urls')),
    path('students/', include('students.urls')),
    path('students/', include('students.urls')),
    path('wages/', include('wages.urls', namespace='wages.wages')),
    path('contacts/', include('contacts.urls', namespace='contacts.contacts')),
    path('', include('mainpage.urls', namespace='mainpage.mainpage')),

    path("accounts/", include("django.contrib.auth.urls")),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from .views import contact_page, contact_form_save

app_name = 'contacts'

urlpatterns = [
    path('', contact_page, name='contact_page'),
    path('form_save/', contact_form_save, name='contact_form_save')
]

subjects/urls.py
from django.urls import path

from teachers.urls import app_name

from .views import SubjectListView, SubjectTemplateView, SubjectAddView,\
        SubjectUptadeView, SubjectDeleteView
# from classboard.views import filter_students_group

app_name = 'subjects'

urlpatterns = [
    path('',SubjectListView.as_view() , name='subjects_view'),
    path('<int:pk>/', SubjectTemplateView.as_view(), name='subjects_view'),
    path('add', SubjectAddView.as_view(), name='subject_add'),
    path('<int:pk>/uptade', SubjectUptadeView.as_view(), name='subject_uptade' ),
    path('<int:pk>/delete', SubjectDeleteView.as_view(), name='subject_delete'),
    # # path('with_teacher/', show_classes_teacher, name='show_classes_teacher'),
    # # path('with_teacher/<int:pk>', show_classes_teacher, name='show_classes_teacher'),
    # # path('with_teacher', class_view, name='class_view'),
    # path('change_teacher/<int:pk>/<int:tpk>', change_teacher, name='change_teacher'),
    # # path('filter_group/', filter_students_group, name='filter_students_group'),
]

teachers/urls.py
from django.urls import path
from .views import view_teachers

app_name = 'teachers'

urlpatterns = [
    path('', view_teachers, name='view_teachers'),
    path('<int:pk>/', view_teachers, name='view_teacher'),
    path('create/', view_teachers, name='view_teacher'),
]

wages/urls.py
from django.urls import path
from wages.views import show_teachers_grid, wage_recalculate

app_name = 'wages'

urlpatterns = [
    path('', show_teachers_grid, name='show_teachers_grid'),
    path('<int:pk>/', show_teachers_grid, name='show_teachers_grid'),
    path('recalculate/<int:pk>/', wage_recalculate, name='wage_recalculate'),
]

templates/layout/base.html
{% url 'teachers:view_teachers' as view_teachers %}
{% url 'subjects:subjects_view' as subjects_view %}
{% url 'classboard_view' as classboard_view %}
{% url 'wages:show_teachers_grid' as show_teachers_grid %}
{% url 'students_view' as students_view %}
{% url 'contacts:contact_page' as contact_page %}

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>
        Великий институт академии Step
    </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">

    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
{% include 'layout/nav.html' %}

{% block content %}
{% endblock content %}
{% include 'layout/footer.html' %}

templates/layout/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Quick Link</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">FAQs & Help</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Gallery</h4>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-1.jpg' %}" alt="">
                        </div>
                        <div class=" col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-2.jpg' %}" alt="">
                        </div>
                        <div class=" col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-3.jpg' %}" alt="">
                        </div>
                        <div class=" col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-2.jpg' %}" alt="">
                        </div>
                        <div class=" col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-3.jpg' %}" alt="">
                        </div>
                        <div class=" col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'img/course-1.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-6">
                        <h4 class="text-white mb-3">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text"
                                   placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">
                                SignUp
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                            Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/wow/wow.min.js' %}"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
        </body>
        </html>

templates/layout/nav.html
{#<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e3f2fd;">#}
{#    <div class="container-fluid">#}
{#      <a class="navbar-brand" href="{% url 'classboard_view' %}">Классная доска</a>#}
{#      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#      </button>#}
{#      <div class="collapse navbar-collapse" id="navbarNav">#}
{#        <ul class="navbar-nav">#}
{#            <li class="nav-item">#}
{#                <a class="nav-link #}
{#                {% if request.path == view_teachers %}#}
{#                    active#}
{#                {% endif %}#}
{#                    " aria-current="page" href="{% url 'teachers:view_teachers' %}">Учителя</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link #}
{#                {% if request.path == class_view %}#}
{#                    active#}
{#                {% endif %}#}
{#                    " aria-current="page" href="{% url 'subjects:class_view' %}">Предметы</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link#}
{#                {% if request.path == student_detail %}#}
{#                    active#}
{#                {% endif %}#}
{#                    " aria-current="page" href="{% url 'students_view' %}">Студенты</a>#}
{#            </li>#}
{#            {% if user.is_authenticated %}#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link #}
{#                    {% if request.path == show_teachers_grid %}#}
{#                        active#}
{#                    {% endif %}#}
{#                        " aria-current="page" href="{% url 'wages:show_teachers_grid' %}">Ведомость</a>#}
{#                </li>#}
{#            {% endif %}#}
{#        </ul>#}
{#        {% if not user.is_authenticated %}#}
{#            <a class="btn btn-outline-success me-2" href="{% url 'login' %}" type="button">Войти</a>#}
{#        {% else %}#}
{#            <a class="btn btn-outline-success me-2" href="{% url 'logout' %}" type="button">Выйти</a>#}
{#        {% endif %}#}
{#    </div>#}
{#</nav>#}
{% load static %}

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Classboard</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a class="nav-item nav-link
                {% if request.path == classboard_view %}#}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'classboard_view' %}">Расписание
            </a>
            <a class="nav-item nav-link
                {% if request.path == view_teachers %}#}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'teachers:view_teachers' %}">Учителя
            </a>
            <a class="nav-item nav-link
                {% if request.path == subjects_view %}#}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'subjects:subjects_view' %}">Предметы
            </a>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle 
                {% if request.path == student_detail %}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'students_view' %}">Студенты
                </a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="{% url 'student_add' %}" class="dropdown-item">Добавить студента</a>
                
                </div>
           
            </div>
            <a class="nav-item nav-link
            {% if request.path == contact_page %}
                active
            {% endif %}
                " aria-current="page" href="{% url 'contacts:contact_page' %}">Контакты
             </a>
             <a class="nav-item nav-link"aria-current="page" href="{% url 'groups_view' %}">Группы
            </a>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block"><i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
<!-- Navbar End -->